#include <stdio.h>
void ReduceSumDriver(double A[], double B[], int rowa, int cola, int dimb, int dim);
void SquareDriver(double A[], double B[], int rowa, int cola);
void TransposeDriver(double A[], double B[], int rowa, int cola);
void DotDriver(double A[], double B[], double C[], int rowa, int cola, int rowb, int colb);
void AddDriver(double A[], double B[], double C[], int row, int col);
void SubDriver(double A[], double B[], double C[], int row, int col);
void ZerosDriver(double A[], int row, int col);
void OnesDriver(double A[], int row, int col);
void GetReducedRow(double A[], double B[], int row, int col, int rowtoget, int coltoremove);
void NegativeDriver(double A[], int size);
void ExpDriver(double A[], double B[], int size);
void LogDriver(double A[], double B[], int size);
void ReduceSumDriver(double A[], double* B, int size);
void MultiplyDriver(double A[], double B[], double C[], int size) ;
void MultiplyDriver(double A[], double B, double C[], int size);
void DivideDriver(double A[], double B, double C[], int size);
void ReplaceRowExceptCol(double A[], double B[], int row, int col, int rowtoreplace, int colexcept);
void MaxASDriver(double A[], double B, double C[], int row, int col);
void DivideDriver( double B, double A[], double C[], int row, int col);
void SetDiagonalDriver(double A[], double B, int row, int col);
void BroadcastArrayToMatrixDriver(double A[], double B[], int row, int col);
void RangeDriver(double A[], int size, int n);
void RandnDriver(double A[], int row, int col);
void MultiplyDriver(double A[], double B, double C[], int row, int col);
void GetRow(double A[], double B[], int row, int col, int rownum);
void GetCol(double A[], double B[], int row, int col, int colnum);
void StackDriver(double A[], double B[], int row, int col);
void SetRow(double A[], double B[], int row, int col, int rownum);
void IsGreaterThanDriver(double A[], double B, int* C, int size);
void IsEqualDriver(int A[], int B[], int C[], int size);
void IsNotEqualDriver(int A[], int B[], int C[], int size);
void AddDriver(double A[], double B, double C[], int size);
void MultiplyDriver(double A[], int B[], double C[], int size);
void CopyDriver(double A[], double B[], int size);
void SetWhereLessThanDriver(double A[], double scalar1, double scalar2, int size);
void ReduceMeanDriver(double A[], double B[], int row, int col, int dimb, int dim);
void DivideDriver(double A[], double B[], double C[], int size);